## car dataset

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.__version__

'2.2.2'

In [4]:
# load the data
df = pd.read_csv('../data/car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [6]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [7]:
#count the uniqu values in fule_type
df['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [8]:
#count  missing values
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [10]:
#find the max vallue in fule efficiency
df['fuel_efficiency_mpg'].max()

41.2

In [ ]:
#  the median  value of horsepower
df['horsepower'].median()

254.0

In [18]:
#the most common value in horsepower 
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [19]:
#fill the missing values in horsepower with the mode value
df['horsepower'].fillna(df['horsepower'].mode()[0], inplace=True)

/tmp/ipykernel_13327/3532592750.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(df['horsepower'].mode()[0], inplace=True)

In [20]:
# find the sum of missing value in horsepower
df['horsepower'].isnull().sum()

0

In [21]:
#find  the  new median of horspower 
df['horsepower'].median()

252.0

In [14]:
#sum of weights
df['vehicle_weight'].sum()

42867540

In [23]:
#select all cars from asia
df[df['origin'] == 'Asia']
#select only columns vehicle-weight and model_year
df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [ ]:
# Select all the cars from Asia
asia_cars = df[df['origin'] == 'Asia']

# Select only columns vehicle_weight and model_year
X = asia_cars[['vehicle_weight', 'model_year']].head(7).to_numpy()

# Compute XTX
XTX = X.T.dot(X)

# Invert XTX
XTX_inv = np.linalg.inv(XTX)

# Create y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# Compute w
w = XTX_inv.dot(X.T).dot(y)

# Sum of all elements of the result
w.sum()